# Provider Configuration for Hub Environment
# NOTE: Terraform block, azurerm and azuread providers are auto-generated by Terragrunt
# See: terraform/terragrunt.hcl (generate_provider block)
# Only environment-specific providers should be defined here

# Kubernetes Provider - connects to existing Dify AKS cluster
provider "kubernetes" {
  host                   = data.azurerm_kubernetes_cluster.dify_aks.kube_config.0.host
  client_certificate     = base64decode(data.azurerm_kubernetes_cluster.dify_aks.kube_config.0.client_certificate)
  client_key             = base64decode(data.azurerm_kubernetes_cluster.dify_aks.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.dify_aks.kube_config.0.cluster_ca_certificate)
}
