# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "subscription_id" {
  type        = string
  description = "Azure subscription ID"
}

variable "tenant_id" {
  type        = string
  description = "Azure AD tenant ID"
  default     = "your-tenant-id-here"  # TODO: Replace with actual tenant ID
}

variable "environment" {
  type        = string
  description = "Environment name (hub, prod, dev)"
}

variable "location" {
  type        = string
  description = "Azure region"
  default     = "northeurope"
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to all resources"
  default     = {}
}
