apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-center-ui
  namespace: cloudmind
  labels:
    app: control-center-ui
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: control-center-ui
  template:
    metadata:
      labels:
        app: control-center-ui
        component: frontend
    spec:
      containers:
      - name: control-center-ui
        image: dxccloudmindx0sa6l.azurecr.io/control-center-ui:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DIFY_API_KEY
          valueFrom:
            secretKeyRef:
              name: dify-api-key
              key: api-key
        - name: NEXT_PUBLIC_DIFY_API_URL
          value: "http://dify-api.dify.svc.cluster.local:5001"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: dify-api-key
  namespace: cloudmind
type: Opaque
stringData:
  api-key: "YOUR_DIFY_API_KEY_HERE"  # Replace with actual key from Dify app
